/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsSubmitRouteImport } from './routes/testimonials-submit'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkRxmenRouteImport } from './routes/work/rxmen'
import { Route as ProjectsZyathiRouteImport } from './routes/projects/zyathi'
import { Route as ProjectsSkillflareRouteImport } from './routes/projects/skillflare'

const TestimonialsSubmitRoute = TestimonialsSubmitRouteImport.update({
  id: '/testimonials-submit',
  path: '/testimonials-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRxmenRoute = WorkRxmenRouteImport.update({
  id: '/work/rxmen',
  path: '/work/rxmen',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsZyathiRoute = ProjectsZyathiRouteImport.update({
  id: '/projects/zyathi',
  path: '/projects/zyathi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSkillflareRoute = ProjectsSkillflareRouteImport.update({
  id: '/projects/skillflare',
  path: '/projects/skillflare',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/testimonials': typeof TestimonialsRoute
  '/testimonials-submit': typeof TestimonialsSubmitRoute
  '/projects/skillflare': typeof ProjectsSkillflareRoute
  '/projects/zyathi': typeof ProjectsZyathiRoute
  '/work/rxmen': typeof WorkRxmenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/testimonials': typeof TestimonialsRoute
  '/testimonials-submit': typeof TestimonialsSubmitRoute
  '/projects/skillflare': typeof ProjectsSkillflareRoute
  '/projects/zyathi': typeof ProjectsZyathiRoute
  '/work/rxmen': typeof WorkRxmenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/testimonials': typeof TestimonialsRoute
  '/testimonials-submit': typeof TestimonialsSubmitRoute
  '/projects/skillflare': typeof ProjectsSkillflareRoute
  '/projects/zyathi': typeof ProjectsZyathiRoute
  '/work/rxmen': typeof WorkRxmenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/testimonials'
    | '/testimonials-submit'
    | '/projects/skillflare'
    | '/projects/zyathi'
    | '/work/rxmen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/testimonials'
    | '/testimonials-submit'
    | '/projects/skillflare'
    | '/projects/zyathi'
    | '/work/rxmen'
  id:
    | '__root__'
    | '/'
    | '/testimonials'
    | '/testimonials-submit'
    | '/projects/skillflare'
    | '/projects/zyathi'
    | '/work/rxmen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TestimonialsSubmitRoute: typeof TestimonialsSubmitRoute
  ProjectsSkillflareRoute: typeof ProjectsSkillflareRoute
  ProjectsZyathiRoute: typeof ProjectsZyathiRoute
  WorkRxmenRoute: typeof WorkRxmenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials-submit': {
      id: '/testimonials-submit'
      path: '/testimonials-submit'
      fullPath: '/testimonials-submit'
      preLoaderRoute: typeof TestimonialsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/rxmen': {
      id: '/work/rxmen'
      path: '/work/rxmen'
      fullPath: '/work/rxmen'
      preLoaderRoute: typeof WorkRxmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/zyathi': {
      id: '/projects/zyathi'
      path: '/projects/zyathi'
      fullPath: '/projects/zyathi'
      preLoaderRoute: typeof ProjectsZyathiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/skillflare': {
      id: '/projects/skillflare'
      path: '/projects/skillflare'
      fullPath: '/projects/skillflare'
      preLoaderRoute: typeof ProjectsSkillflareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestimonialsRoute: TestimonialsRoute,
  TestimonialsSubmitRoute: TestimonialsSubmitRoute,
  ProjectsSkillflareRoute: ProjectsSkillflareRoute,
  ProjectsZyathiRoute: ProjectsZyathiRoute,
  WorkRxmenRoute: WorkRxmenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
